server:
  port: 6663

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/photo_app_db
    username: root
    password: sa123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  devtools:
    livereload:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6661/eureka
    enabled: true

application:
    pepper: secret_value
